//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceptionReporting.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExceptionReporting.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Copied to clipboard.
        /// </summary>
        internal static string Copied_to_clipboard {
            get {
                return ResourceManager.GetString("Copied to clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Copy details.
        /// </summary>
        internal static string Copy_details {
            get {
                return ResourceManager.GetString("Copy details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error Report.
        /// </summary>
        internal static string ErrorReport {
            get {
                return ResourceManager.GetString("ErrorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a If this problem persists, please contact {0} support..
        /// </summary>
        internal static string ExceptionReportView_PopulateReportInfo_If_this_problem_persists__please_contact__0__support_ {
            get {
                return ResourceManager.GetString("ExceptionReportView_PopulateReportInfo_If_this_problem_persists__please_contact__" +
                        "0__support_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error sending report.
        /// </summary>
        internal static string ExceptionReportView_ShowError_Error_sending_report {
            get {
                return ResourceManager.GetString("ExceptionReportView_ShowError_Error_sending_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Less Detail.
        /// </summary>
        internal static string ExceptionReportView_ToggleShowFullDetail_Less_Detail {
            get {
                return ResourceManager.GetString("ExceptionReportView_ToggleShowFullDetail_Less_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a More Detail.
        /// </summary>
        internal static string ExceptionReportView_ToggleShowFullDetail_More_Detail {
            get {
                return ResourceManager.GetString("ExceptionReportView_ToggleShowFullDetail_More_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clipboard copy failed.
        /// </summary>
        internal static string Failed_to_copy_to_clipboard {
            get {
                return ResourceManager.GetString("Failed to copy to clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Failed to send report.
        /// </summary>
        internal static string Failed_to_send_report {
            get {
                return ResourceManager.GetString("Failed to send report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Failed trying to report an Error.
        /// </summary>
        internal static string Failed_trying_to_report_an_Error {
            get {
                return ResourceManager.GetString("Failed trying to report an Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please enter a brief explanation of events leading up to this exception.
        /// </summary>
        internal static string Please_enter_a_brief_explanation_of_events_leading_up_to_this_exception {
            get {
                return ResourceManager.GetString("Please enter a brief explanation of events leading up to this exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Report sent.
        /// </summary>
        internal static string Report_sent {
            get {
                return ResourceManager.GetString("Report sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Test Loc.
        /// </summary>
        internal static string TestLoc {
            get {
                return ResourceManager.GetString("TestLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The following details can be used to obtain support for this application.
        /// </summary>
        internal static string The_following_details_can_be_used_to_obtain_support_for_this_application {
            get {
                return ResourceManager.GetString("The following details can be used to obtain support for this application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a to {0}.
        /// </summary>
        internal static string to__0_ {
            get {
                return ResourceManager.GetString("to {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unable to save file.
        /// </summary>
        internal static string Unable_to_save_file {
            get {
                return ResourceManager.GetString("Unable to save file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unable to setup.
        /// </summary>
        internal static string Unable_to_setup {
            get {
                return ResourceManager.GetString("Unable to setup", resourceCulture);
            }
        }
    }
}
